"use strict";

window.AppConfig = {
  LANGUAGES: [
    { code: "tr-TR", name: "Türkçe", country: "tr" },
    { code: "en-US", name: "English", country: "us" },
    { code: "de-DE", name: "Deutsch", country: "de" },
    { code: "fr-FR", name: "Français", country: "fr" },
    { code: "es-ES", name: "Español", country: "es" },
    { code: "it-IT", name: "Italiano", country: "it" },
    { code: "pt-BR", name: "Português (BR)", country: "br" },
    { code: "ru-RU", name: "Русский", country: "ru" },
    { code: "ar-SA", name: "العربية", country: "sa" },
    { code: "zh-CN", name: "中文", country: "cn" },
  ],
  CURRENCIES: ["TRY", "USD", "EUR", "GBP", "JPY", "SAR", "AED", "RUB", "CNY", "INR"],
  CURRENCY_META: {
    TRY: { symbol: "₺", icon: "🇹🇷", fallbackName: "Türk lirası" },
    USD: { symbol: "$", icon: "🇺🇸", fallbackName: "US dollar" },
    EUR: { symbol: "€", icon: "🇪🇺", fallbackName: "Euro" },
    GBP: { symbol: "£", icon: "🇬🇧", fallbackName: "Pound sterling" },
    JPY: { symbol: "¥", icon: "🇯🇵", fallbackName: "Japanese yen" },
    SAR: { symbol: "﷼", icon: "🇸🇦", fallbackName: "Saudi riyal" },
    AED: { symbol: "د.إ", icon: "🇦🇪", fallbackName: "UAE dirham" },
    RUB: { symbol: "₽", icon: "🇷🇺", fallbackName: "Russian ruble" },
    CNY: { symbol: "¥", icon: "🇨🇳", fallbackName: "Chinese yuan" },
    INR: { symbol: "₹", icon: "🇮🇳", fallbackName: "Indian rupee" },
  },
  CURRENCY_FLAG_COUNTRY: {
    TRY: "tr",
    USD: "us",
    EUR: "eu",
    GBP: "gb",
    JPY: "jp",
    SAR: "sa",
    AED: "ae",
    RUB: "ru",
    CNY: "cn",
    INR: "in",
  },
  UI_TEXT: {
    "tr-TR": { title: "Profesyonel Tutar Metin Dönüştürücü", subtitle: "10 dil ve 10 para birimi desteği. Dil ve para birimini ayrı seçebilirsiniz.", appLanguageLabel: "Uygulama Dili", outputLanguageLabel: "Sonuç Dili", currencyLabel: "Para Birimi", majorLabel: "Ana Tutar", minorLabel: "Alt Birim", resultTitle: "Sonuç", convertBtn: "Yazıya Çevir", copyBtn: "Sonucu Kopyala", copiedBtn: "Kopyalandı", success: "Dönüşüm tamamlandı.", copySuccess: "Sonuç panoya kopyalandı.", majorRequired: "Ana tutar alanı zorunludur.", majorDigits: "Ana tutar alanına yalnızca sayı girin.", minorDigits: "Alt birim alanına yalnızca sayı girin.", majorTooBig: "Ana tutar çok büyük.", conversionError: "Dönüştürme sırasında beklenmeyen hata oluştu.", copyFailed: "Panoya kopyalanamadı." },
    "en-US": { title: "Professional Amount Text Converter", subtitle: "Supports 10 languages and 10 currencies. Language and currency are independent.", appLanguageLabel: "App Language", outputLanguageLabel: "Output Language", currencyLabel: "Currency", majorLabel: "Major Unit", minorLabel: "Minor Unit", resultTitle: "Result", convertBtn: "Convert", copyBtn: "Copy Result", copiedBtn: "Copied", success: "Conversion completed.", copySuccess: "Result copied to clipboard.", majorRequired: "Major unit is required.", majorDigits: "Major unit accepts digits only.", minorDigits: "Minor unit accepts digits only.", majorTooBig: "Major unit is too large.", conversionError: "Unexpected conversion error.", copyFailed: "Failed to copy." },
    "de-DE": { title: "Professioneller Betrag-Text-Konverter", subtitle: "10 Sprachen und 10 Währungen. Sprache und Währung sind unabhängig.", appLanguageLabel: "App-Sprache", outputLanguageLabel: "Ausgabesprache", currencyLabel: "Währung", majorLabel: "Haupteinheit", minorLabel: "Untereinheit", resultTitle: "Ergebnis", convertBtn: "Umwandeln", copyBtn: "Ergebnis kopieren", copiedBtn: "Kopiert", success: "Umwandlung abgeschlossen.", copySuccess: "Ergebnis wurde kopiert.", majorRequired: "Haupteinheit ist erforderlich.", majorDigits: "Nur Ziffern in der Haupteinheit.", minorDigits: "Nur Ziffern in der Untereinheit.", majorTooBig: "Haupteinheit ist zu groß.", conversionError: "Unerwarteter Umwandlungsfehler.", copyFailed: "Kopieren fehlgeschlagen." },
    "fr-FR": { title: "Convertisseur Professionnel de Montant en Texte", subtitle: "Prend en charge 10 langues et 10 devises. Langue et devise sont indépendantes.", appLanguageLabel: "Langue de l'app", outputLanguageLabel: "Langue de sortie", currencyLabel: "Devise", majorLabel: "Unité principale", minorLabel: "Sous-unité", resultTitle: "Résultat", convertBtn: "Convertir", copyBtn: "Copier le résultat", copiedBtn: "Copié", success: "Conversion terminée.", copySuccess: "Résultat copié.", majorRequired: "Unité principale obligatoire.", majorDigits: "Seuls les chiffres sont autorisés.", minorDigits: "Seuls les chiffres sont autorisés.", majorTooBig: "Unité principale trop grande.", conversionError: "Erreur de conversion inattendue.", copyFailed: "Échec de la copie." },
    "es-ES": { title: "Convertidor Profesional de Importe a Texto", subtitle: "Soporta 10 idiomas y 10 monedas. Idioma y moneda son independientes.", appLanguageLabel: "Idioma de la app", outputLanguageLabel: "Idioma de salida", currencyLabel: "Moneda", majorLabel: "Unidad principal", minorLabel: "Subunidad", resultTitle: "Resultado", convertBtn: "Convertir", copyBtn: "Copiar resultado", copiedBtn: "Copiado", success: "Conversión completada.", copySuccess: "Resultado copiado.", majorRequired: "La unidad principal es obligatoria.", majorDigits: "Solo se permiten dígitos.", minorDigits: "Solo se permiten dígitos.", majorTooBig: "La unidad principal es demasiado grande.", conversionError: "Error inesperado de conversión.", copyFailed: "No se pudo copiar." },
    "it-IT": { title: "Convertitore Professionale di Importo in Testo", subtitle: "Supporta 10 lingue e 10 valute. Lingua e valuta sono indipendenti.", appLanguageLabel: "Lingua app", outputLanguageLabel: "Lingua output", currencyLabel: "Valuta", majorLabel: "Unità principale", minorLabel: "Sotto-unità", resultTitle: "Risultato", convertBtn: "Converti", copyBtn: "Copia risultato", copiedBtn: "Copiato", success: "Conversione completata.", copySuccess: "Risultato copiato.", majorRequired: "Unità principale obbligatoria.", majorDigits: "Sono consentite solo cifre.", minorDigits: "Sono consentite solo cifre.", majorTooBig: "Unità principale troppo grande.", conversionError: "Errore di conversione imprevisto.", copyFailed: "Copia non riuscita." },
    "pt-BR": { title: "Conversor Profissional de Valor em Texto", subtitle: "Suporta 10 idiomas e 10 moedas. Idioma e moeda são independentes.", appLanguageLabel: "Idioma do app", outputLanguageLabel: "Idioma de saída", currencyLabel: "Moeda", majorLabel: "Unidade principal", minorLabel: "Subunidade", resultTitle: "Resultado", convertBtn: "Converter", copyBtn: "Copiar resultado", copiedBtn: "Copiado", success: "Conversão concluída.", copySuccess: "Resultado copiado.", majorRequired: "Unidade principal obrigatória.", majorDigits: "Apenas dígitos são permitidos.", minorDigits: "Apenas dígitos são permitidos.", majorTooBig: "Unidade principal muito grande.", conversionError: "Erro inesperado na conversão.", copyFailed: "Falha ao copiar." },
    "ru-RU": { title: "Профессиональный Преобразователь Суммы в Текст", subtitle: "Поддержка 10 языков и 10 валют. Язык и валюта выбираются отдельно.", appLanguageLabel: "Язык приложения", outputLanguageLabel: "Язык результата", currencyLabel: "Валюта", majorLabel: "Основная единица", minorLabel: "Дробная единица", resultTitle: "Результат", convertBtn: "Преобразовать", copyBtn: "Копировать результат", copiedBtn: "Скопировано", success: "Преобразование завершено.", copySuccess: "Результат скопирован.", majorRequired: "Основная единица обязательна.", majorDigits: "Разрешены только цифры.", minorDigits: "Разрешены только цифры.", majorTooBig: "Слишком большое значение.", conversionError: "Непредвиденная ошибка преобразования.", copyFailed: "Не удалось скопировать." },
    "ar-SA": { title: "محول المبلغ إلى نص احترافي", subtitle: "يدعم 10 لغات و10 عملات. اللغة والعملة مستقلتان.", appLanguageLabel: "لغة التطبيق", outputLanguageLabel: "لغة النتيجة", currencyLabel: "العملة", majorLabel: "الوحدة الرئيسية", minorLabel: "الوحدة الفرعية", resultTitle: "النتيجة", convertBtn: "تحويل", copyBtn: "نسخ النتيجة", copiedBtn: "تم النسخ", success: "اكتمل التحويل.", copySuccess: "تم نسخ النتيجة.", majorRequired: "الوحدة الرئيسية مطلوبة.", majorDigits: "يُسمح بالأرقام فقط.", minorDigits: "يُسمح بالأرقام فقط.", majorTooBig: "القيمة كبيرة جدًا.", conversionError: "حدث خطأ غير متوقع.", copyFailed: "فشل النسخ." },
    "zh-CN": { title: "专业金额转文字转换器", subtitle: "支持 10 种语言和 10 种货币，语言与货币独立选择。", appLanguageLabel: "应用语言", outputLanguageLabel: "结果语言", currencyLabel: "货币", majorLabel: "主单位", minorLabel: "次单位", resultTitle: "结果", convertBtn: "转换", copyBtn: "复制结果", copiedBtn: "已复制", success: "转换完成。", copySuccess: "结果已复制。", majorRequired: "主单位为必填。", majorDigits: "主单位只能输入数字。", minorDigits: "次单位只能输入数字。", majorTooBig: "主单位数值过大。", conversionError: "发生意外转换错误。", copyFailed: "复制失败。" },
  },
  TEMPLATE_UI_LABELS: {
    "tr-TR": { templateLabel: "Belge Şablonu", officialModeLabel: "Resmi Çıktı Modu (YALNIZ ...)" },
    "en-US": { templateLabel: "Document Template", officialModeLabel: "Official Output Mode (ONLY ...)" },
    "de-DE": { templateLabel: "Dokumentvorlage", officialModeLabel: "Offizieller Ausgabemodus (NUR ...)" },
    "fr-FR": { templateLabel: "Modèle de document", officialModeLabel: "Mode de sortie officiel (SEULEMENT ...)" },
    "es-ES": { templateLabel: "Plantilla de documento", officialModeLabel: "Modo de salida oficial (SOLO ...)" },
    "it-IT": { templateLabel: "Modello documento", officialModeLabel: "Modalità output ufficiale (SOLO ...)" },
    "pt-BR": { templateLabel: "Modelo de documento", officialModeLabel: "Modo de saída oficial (SOMENTE ...)" },
    "ru-RU": { templateLabel: "Шаблон документа", officialModeLabel: "Официальный режим вывода (ТОЛЬКО ...)" },
    "ar-SA": { templateLabel: "قالب المستند", officialModeLabel: "وضع الإخراج الرسمي (فقط ...)" },
    "zh-CN": { templateLabel: "文档模板", officialModeLabel: "正式输出模式（仅限 ...）" },
  },
  LANG_KEY_BY_CODE: { "tr-TR": "tr", "en-US": "en", "de-DE": "de", "fr-FR": "fr", "es-ES": "es", "it-IT": "it", "pt-BR": "pt", "ru-RU": "ru", "ar-SA": "ar", "zh-CN": "zh" },
  MINOR_FALLBACK_BY_LANG: { tr: "kuruş", en: "cent", de: "Cent", fr: "centime", es: "centavo", it: "centesimo", pt: "centavo", ru: "копейка", ar: "جزء", zh: "分" },
  CURRENCY_UNITS: {
    TRY: { tr: { major: "Türk lirası", minor: "kuruş" }, en: { major: "Turkish lira", minor: "kurush" }, de: { major: "Türkische Lira", minor: "Kurus" }, fr: { major: "livre turque", minor: "kurush" }, es: { major: "lira turca", minor: "kurus" }, it: { major: "lira turca", minor: "kurus" }, pt: { major: "lira turca", minor: "kurus" }, ru: { major: "турецкая лира", minor: "куруш" }, ar: { major: "ليرة تركية", minor: "قرش" }, zh: { major: "土耳其里拉", minor: "库鲁什" } },
    USD: { tr: { major: "Amerikan doları", minor: "sent" }, default: { minor: "cent" } },
    EUR: { tr: { major: "avro", minor: "sent" }, default: { minor: "cent" } },
    GBP: { tr: { major: "sterlin", minor: "pence" }, default: { minor: "pence" } },
    JPY: { tr: { major: "Japon yeni", minor: "sen" }, default: { minor: "sen" } },
    SAR: { tr: { major: "Suudi riyali", minor: "halala" }, default: { minor: "halala" } },
    AED: { tr: { major: "BAE dirhemi", minor: "fils" }, default: { minor: "fils" } },
    RUB: { tr: { major: "Rus rublesi", minor: "kapik" }, default: { minor: "kopeck" } },
    CNY: { tr: { major: "Çin yuanı", minor: "fen" }, default: { minor: "fen" } },
    INR: { tr: { major: "Hindistan rupisi", minor: "paise" }, default: { minor: "paise" } },
  },
  CURRENCY_UNIT_FORMS: {
    TRY: {
      "tr-TR": { major: ["Türk lirası", "Türk lirası"], minor: ["kuruş", "kuruş"] },
      "en-US": { major: ["Turkish lira", "Turkish liras"], minor: ["kurush", "kurush"] },
      "de-DE": { major: ["Türkische Lira", "Türkische Lira"], minor: ["Kurus", "Kurus"] },
      "fr-FR": { major: ["livre turque", "livres turques"], minor: ["kurush", "kurush"] },
      "es-ES": { major: ["lira turca", "liras turcas"], minor: ["kurus", "kurus"] },
      "it-IT": { major: ["lira turca", "lire turche"], minor: ["kurus", "kurus"] },
      "pt-BR": { major: ["lira turca", "liras turcas"], minor: ["kurus", "kurus"] },
      "ru-RU": { major: ["турецкая лира", "турецкие лиры", "турецких лир"], minor: ["куруш", "куруша", "курушей"] },
      "ar-SA": { major: ["ليرة تركية", "ليرة تركية"], minor: ["قرش", "قرش"] },
      "zh-CN": { major: ["土耳其里拉", "土耳其里拉"], minor: ["库鲁什", "库鲁什"] },
    },
  },
  STYLE_GUIDE_TERMS: {
    "en-US": {
      "Turkish liras": "Turkish lira",
    },
    "de-DE": {
      Kurus: "Kurus",
    },
  },
  ONES: ["", "bir", "iki", "üç", "dört", "beş", "altı", "yedi", "sekiz", "dokuz"],
  TENS: ["", "on", "yirmi", "otuz", "kırk", "elli", "altmış", "yetmiş", "seksen", "doksan"],
  SCALES: ["", "bin", "milyon", "milyar", "trilyon", "katrilyon"],
  STORAGE_KEYS: { history: "amountHistoryV2", appLang: "appLanguageV1", outputLang: "outputLanguageV1", currency: "currencyV1", theme: "preferredTheme" },
};
